config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('yk.urls')),
    path('accounts/', include('allauth.urls')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

yk/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import *

app_name = 'yk'

urlpatterns = [
    path('', main, name='main'),
    path('join/start', join_start, name='join_start'),
    path('join/done', join_done, name='join_done'),
    path('join/1', join1, name='join1'),
    path('join/2', join2, name='join2'),
    path('join/3', join3, name='join3'),
    path('profile/<int:pk>', profile, name='profile'),
    path('my_profile', my_profile, name='my_profile'),
    path('friends', friends, name='friends'),
    path('friends/accept/<int:pk>', accept_friends, name='accept_friends'),
    path('friends/follow/<int:pk>', follow, name='follow'),
    path('location/', location, name='location'),
    path('ask/', ask, name='ask'),
    path('my_ask', my_ask, name='my_ask'),
    path('answer/', answer, name='answer'),
    path('report_user/<int:pk>', report_user, name='report_user'),
    path('report_ask/<int:pk>', report_ask, name='report_ask'),
]

yk/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.conf import settings


class Interest(models.Model):
    interest = models.CharField(verbose_name='관심사', max_length=50)

    def __str__(self):
        return self.interest


class Profile(models.Model):
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    profile_image = models.ImageField(
        upload_to='profile_images', blank=True, null=True)
    phone_number = models.IntegerField(
        verbose_name='전화번호', blank=True, null=True)
    nickname = models.CharField(
        verbose_name='닉네임', max_length=20, blank=True, null=True)
    school = models.CharField(
        verbose_name='학교', max_length=20, blank=True, null=True)
    block_school = models.BooleanField(
        verbose_name='학교 안보이기', default=False, blank=True, null=True)
    age = models.IntegerField(verbose_name='나이', blank=True, null=True)
    gender = models.CharField(
        verbose_name='성별', max_length=20, blank=True, null=True)
    goal = models.CharField(
        verbose_name='목표', max_length=100, blank=True, null=True)
    major = models.CharField(
        verbose_name='전공', max_length=50, blank=True, null=True)
    bio = models.TextField(verbose_name='자기 소개', blank=True, null=True)
    mbti = models.CharField(verbose_name='mbti',
                            max_length=50, blank=True, null=True)
    interest = models.ManyToManyField(
        Interest, related_name='interests', blank=True)
    club = models.CharField(
        verbose_name='동아리', max_length=150, blank=True, null=True)
    user_report = models.ManyToManyField(
        settings.AUTH_USER_MODEL, related_name='user_report', blank=True)
    following = models.ManyToManyField(
        settings.AUTH_USER_MODEL, related_name='following', blank=True)
    follower = models.ManyToManyField(
        settings.AUTH_USER_MODEL, related_name='follower', blank=True)
    today_friends = models.ManyToManyField(
        settings.AUTH_USER_MODEL, related_name='today_friends', blank=True)
    yesterday_friends = models.ManyToManyField(
        settings.AUTH_USER_MODEL, related_name='yesterday_friends', blank=True)
    latitude = models.CharField(
        verbose_name='위도', max_length=100, null=True, blank=True)
    longitude = models.CharField(
        verbose_name='경도', max_length=100, null=True, blank=True)
    address = models.CharField(
        verbose_name='주소', max_length=100, null=True, blank=True)

    def __str__(self):
        return self.user.username


class Ask(models.Model):
    question = models.CharField(
        verbose_name='question', max_length=100, blank=True, null=True)
    ask_to = models.ForeignKey(
        settings.AUTH_USER_MODEL, related_name='ask_to', on_delete=models.CASCADE)
    ask_from = models.ForeignKey(
        settings.AUTH_USER_MODEL, related_name='ask_from', on_delete=models.CASCADE)
    ask_report = models.ForeignKey(
        settings.AUTH_USER_MODEL, related_name='ask_report', on_delete=models.CASCADE, blank=True, null=True)

    def __str__(self):
        return self.question


class Answer(models.Model):
    answer = models.TextField(verbose_name='answer', blank=True, null=True)
    ask = models.ForeignKey(Ask, related_name='ask', on_delete=models.CASCADE)
    answered_at = models.DateField(auto_now_add=True, blank=True, null=True)

    def __str__(self):
        return self.answer


class Message(models.Model):
    message = models.CharField(
        verbose_name='친구 신청 메시지', max_length=150, blank=True, null=True)
    message_to = models.ForeignKey(
        settings.AUTH_USER_MODEL, related_name='message_to', on_delete=models.CASCADE)
    message_from = models.ForeignKey(
        settings.AUTH_USER_MODEL, related_name='message_from', on_delete=models.CASCADE)
    message_report = models.ForeignKey(
        settings.AUTH_USER_MODEL, related_name='message_report', on_delete=models.CASCADE, blank=True, null=True)

yk/views.py
from celery import Celery
from celery.schedules import crontab
import schedule
import time
import threading
import requests
from urllib.parse import urlparse
from django.http import JsonResponse
from django.http import HttpResponse
from django.views.decorators.csrf import csrf_exempt
import random
from django.shortcuts import render, redirect
from .models import *
from django.contrib.auth.models import User, AnonymousUser
import json


def main(request):
    admin = User.objects.get(id=1)
    user_list = list(User.objects.all())
    try:
        user_list.remove(request.user)
    except:
        pass
    user_list.remove(admin)
    random_user = random.choice(user_list)

    user = request.user
    ctx = {
        'user': user,
        'random_user': random_user,
    }
    return render(request, 'main.html', ctx)


def join_start(request):
    user = request.user
    ctx = {
        'user': user
    }
    return render(request, 'join_start.html', ctx)


def join1(request):
    user = request.user
    if request.method == 'GET':
        try:
            if Profile.objects.get(user=user):
                pass
        except:
            new_profile = Profile()
            new_profile.user = request.user
            new_profile.save()

        ctx = {
            'user': user
        }
        return render(request, 'join1.html', ctx)
    elif request.method == 'POST':
        try:
            block_school = request.POST['block_school']
            if block_school == 'block':
                block_school = True
        except:
            block_school = False

        my_profile = Profile.objects.get(user=user)
        my_profile.profile_image = request.FILES['image']
        my_profile.phone_number = request.POST['onlyNumber']
        my_profile.school = request.POST['school']
        my_profile.block_school = block_school
        my_profile.age = request.POST['age']
        my_profile.mbti = request.POST['mbti']
        my_profile.gender = request.POST['gender']
        my_profile.bio = request.POST['introduce']

        my_profile.save()

        ctx = {
            'user': user
        }
        return render(request, 'join2.html', ctx)


def join2(request):
    user = request.user
    if request.method == 'GET':
        ctx = {
            'user': user
        }
        return render(request, 'join2.html', ctx)
    elif request.method == 'POST':
        my_profile = Profile.objects.get(user=user)
        my_profile.goal = request.POST['introduce']
        my_profile.major = request.POST['self_info']

        my_profile.save()

        ctx = {
            'user': user
        }
        return render(request, 'join3.html', ctx)


def join3(request):
    user = request.user
    if request.method == 'GET':
        ctx = {
            'user': user
        }
        return render(request, 'join3.html', ctx)
    elif request.method == 'POST':
        interest_list = request.POST['self_info']
        interest_num = len(interest_list.split('#'))
        for i in range(1, interest_num):
            globals()["new_interest{}".format(i)] = Interest()
            globals()["new_interest{}".format(
                i)].interest = interest_list.split('#')[i]
            globals()["new_interest{}".format(i)].save()

        my_profile = Profile.objects.get(user=user)
        my_profile.club = request.POST['introduce']
        for i in range(1, interest_num):
            my_profile.interest.add(globals()["new_interest{}".format(i)])
        my_profile.save()

        ctx = {
            'user': user
        }
        return render(request, 'join_done.html', ctx)


def join_done(request):
    user = request.user
    ctx = {
        'user': user
    }
    return render(request, 'join_done.html', ctx)


def social_login(request):
    user = request.user
    ctx = {
        'user': user
    }
    return render(request, 'login.html', ctx)


def profile(request, pk):

    friend = User.objects.get(id=pk)
    admin = User.objects.get(id=1)
    user_list = list(User.objects.all())
    user_list.remove(friend)
    try:
        user_list.remove(request.user)
    except:
        pass
    user_list.remove(admin)

    random_user = random.choice(user_list)

    friend_profile = Profile.objects.get(user=friend)

    asks_whole = list(Ask.objects.filter(ask_to=friend))
    ask_mine = list(Ask.objects.filter(ask_to=friend, ask_from=request.user))
    asks = []
    for i in range(len(asks_whole)):
        if len(asks_whole[i].ask.all()) != 0 and asks[i].ask_report == None:
            asks.append(asks_whole[i])
    for i in range(len(ask_mine)):
        asks.append(ask_mine[i])

    ctx = {
        'friend': friend,
        'friend_profile': friend_profile,
        'asks': asks,
        'random_user': random_user
    }
    return render(request, 'profile.html', ctx)


def my_ask(request):
    asks = list(Ask.objects.filter(ask_to=request.user))
    my_ask = []
    for i in range(len(asks)):
        if len(asks[i].ask.all()) == 0 and asks[i].ask_report == None:
            my_ask.append(asks[i])
    ctx = {
        'my_ask': my_ask
    }
    return render(request, 'my_ask.html', ctx)


def my_profile(request):
    user = request.user
    profile = Profile.objects.get(user=user)
    asks = list(Ask.objects.filter(ask_to=user, ask_report=None))
    ctx = {
        'user': user,
        'profile': profile,
        'asks': asks
    }
    return render(request, 'my_profile.html', ctx)


@ csrf_exempt
def ask(request):
    if request.method == 'POST':
        req = json.loads(request.body)
        friend_id = req['id']
        question = req['question']
        friend = User.objects.get(id=friend_id)
        new_ask = Ask()
        new_ask.question = question
        new_ask.ask_to = friend
        new_ask.ask_from = request.user
        new_ask.save()
        return JsonResponse({'friend_id': friend_id, 'question': question})


@ csrf_exempt
def answer(request):
    if request.method == 'POST':
        req = json.loads(request.body)
        ask_id = req['id']
        answer = req['answer']
        this_ask = Ask.objects.get(id=ask_id)
        new_answer = Answer()
        new_answer.ask = this_ask
        new_answer.answer = answer
        new_answer.save()
        return JsonResponse({'ask_id': ask_id, 'answer': answer})


def friends(request):
    user = request.user
    profile = Profile.objects.get(user=user)
    followings = profile.following.all()
    following_list = []
    for following in followings:
        following_list.append(Profile.objects.get(user=following))

    followers = profile.follower.all()
    follower_list = []
    for follower in followers:
        follower_list.append(Profile.objects.get(user=follower))

    today_friends = profile.today_friends.all()
    today_friends_list = []
    for today_friend in today_friends:
        today_friends_list.append(Profile.objects.get(user=today_friend))

    yesterday_friends = profile.yesterday_friends.all()
    yesterday_friends_list = []
    for yesterday_friend in yesterday_friends:
        yesterday_friends_list.append(
            Profile.objects.get(user=yesterday_friend))

    ctx = {
        'user': user,
        'profile': profile,
        'following_list': following_list,
        'follower_list': follower_list,
        'today_friends_list': today_friends_list,
        'yesterday_friends_list': yesterday_friends_list,
    }
    return render(request, 'friends.html', ctx)


def accept_friends(request, pk):
    user = request.user
    friend = User.objects.get(id=pk)

    profile = Profile.objects.get(user=user)
    profile.today_friends.add(friend)
    profile.follower.remove(friend)
    profile.save()

    followings = profile.following.all()
    following_list = []
    for following in followings:
        following_list.append(Profile.objects.get(user=following))

    followers = profile.follower.all()
    follower_list = []
    for follower in followers:
        follower_list.append(Profile.objects.get(user=follower))

    today_friends = profile.today_friends.all()
    today_friends_list = []
    for today_friend in today_friends:
        today_friends_list.append(Profile.objects.get(user=today_friend))

    yesterday_friends = profile.yesterday_friends.all()
    yesterday_friends_list = []
    for yesterday_friend in yesterday_friends:
        yesterday_friends_list.append(
            Profile.objects.get(user=yesterday_friend))

    ctx = {
        'user': user,
        'profile': profile,
        'following_list': following_list,
        'follower_list': follower_list,
        'today_friends_list': today_friends_list,
        'yesterday_friends_list': yesterday_friends_list,

    }
    return render(request, 'friends.html', ctx)


def follow(request, pk):
    user = request.user
    friend = User.objects.get(id=pk)
    friend_profile = Profile.objects.get(user=friend)
    friend_profile.follower.add(user)
    friend_profile.save()
    return redirect('/profile/'+str(friend.id))


@ csrf_exempt
def location(request):
    req = json.loads(request.body)
    latitude = req['latitude']
    longitude = req['longitude']
    address = req['address']
    user = request.user
    profile = Profile.objects.get(user=user)
    profile.latitude = latitude
    profile.longitude = longitude
    profile.address = address
    profile.save()
    return JsonResponse({'latitude': latitude, 'longitude': longitude, 'address': address})


def report_user(request, pk):
    friend = User.objects.get(id=pk)
    friend_profile = Profile.objects.get(user=friend)
    friend_profile.user_report.add(request.user)
    friend_profile.save()
    return redirect('/')


def report_ask(request, pk):
    ask = Ask.objects.get(id=pk)
    ask.ask_report = request.user
    ask.save()
    return redirect('/')


def printhello():
    print('hello')


schedule.every().day.at('21:09').do(printhello)

yk/templates/friends.html
<h3>friends</h3>
<div>
    <h3>내가 받은 친구</h3>
    {% for follower in follower_list %}
    <a href="{% url 'yk:profile' follower.user.id%}"><p>{{follower.nickname}}</p></a>
    <img src="{{follower.profile_image.url}}" alt="" width="100" />
    <a href="{% url 'yk:accept_friends' follower.user.id%}"><button>FRIENDS!</button></a>

    {% endfor %}
</div>
<div>
    <h3>내가 보낸 친구</h3>
    {% for following in following_list %}
    <a href="{% url 'yk:profile' following.user.id%}"><p>{{following.nickname}}</p></a>
    <img src="{{following.profile_image.url}}" alt="" width="100" />
    {% endfor %}
</div>
<div>
    <h3>오늘 친구</h3>
    {% for today_friend in today_friends_list %}
    <a href="{% url 'yk:profile' today_friend.user.id%}"><p>{{today_friend.nickname}}</p></a>
    <img src="{{today_friend.profile_image.url}}" alt="" width="100" />

    {% endfor %}
</div>
<div>
    <h3>어제 친구</h3>
    {% for yesterday_friend in yesterday_friends_list %}
    <a href="{% url 'yk:profile' yesterday_friend.user.id%}"><p>{{yesterday_friend.nickname}}</p></a>
    <img src="{{yesterday_friend.profile_image.url}}" alt="" width="100" />

    {% endfor %}
</div>

yk/templates/join_done.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Document</title>
    </head>
    <body>
        <p>done!</p>
        <a href="https://open.kakao.com/o/sWKOALmd">학교 인증하기</a>
    </body>
</html>

yk/templates/join_start.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Document</title>
    </head>
    <body>
        <a href="{% url 'yk:join1'%}"> join_start!</a>
    </body>
</html>

yk/templates/login.html
{% load socialaccount %} {% providers_media_js %}

<p>{{user}}</p>

<a href="/accounts/signup">회원가입</a>

<a href="{% provider_login_url 'google' %}">구글 로그인</a>

<a href="{% provider_login_url 'kakao' method='oauth2' %}">카카오 로그인</a>

yk/templates/main.html
{% load socialaccount %} {% providers_media_js %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Document</title>
    </head>
    <body>
        <p>{{user}}</p>

        <a href="/accounts/signup">회원가입</a>

        <a href="{% provider_login_url 'google' %}">구글 로그인</a>

        <a href="{% provider_login_url 'kakao' method='oauth2' %}">카카오 로그인</a>

        <a href="/accounts/logout">로그아웃</a>

        <a href="{% url 'yk:profile' random_user.id%}">친구찾기</a>

        <a href="{% url 'yk:my_profile' %}">내 프로필</a>

        <a href="{% url 'yk:join_start' %}">join</a>

        <div id="map" style="width: 500px; height: 400px"></div>
    </body>

    <script
        type="text/javascript"
        src="//dapi.kakao.com/v2/maps/sdk.js?appkey=10ac4044de47db57c8b24d1940511876&libraries=services"
    ></script>
    <script></script>
    <script>
        function getLocation() {
            if (navigator.geolocation) {
                // GPS를 지원하면
                navigator.geolocation.getCurrentPosition(
                    function (position) {
                        const latitude = position.coords.latitude;
                        const longitude = position.coords.longitude;
                        const coords = position.coords;

                        var geocoder = new kakao.maps.services.Geocoder();
                        function searchAddrFromCoords(coords, callback) {
                            // 좌표로 행정동 주소 정보를 요청합니다
                            geocoder.coord2RegionCode(coords.longitude, coords.latitude, callback);
                        }
                        searchAddrFromCoords(coords, displayCenterInfo);

                        function displayCenterInfo(result, status) {
                            if (status === kakao.maps.services.Status.OK) {
                                for (var i = 0; i < result.length; i++) {
                                    // 행정동의 region_type 값은 'H' 이므로
                                    if (result[i].region_type === "H") {
                                        const address = result[0].region_2depth_name;
                                        const request = new XMLHttpRequest();
                                        const url = "location/";
                                        request.open("POST", url, true);
                                        request.setRequestHeader("Content-Type", "application/x-www-form-urlencoded");
                                        request.send(JSON.stringify({ latitude, longitude, address }));
                                        console.log(latitude + " " + longitude + " " + address);
                                        break;
                                    }
                                }
                            }
                        }
                    },
                    function (error) {
                        console.error(error);
                    },
                    {
                        enableHighAccuracy: false,
                        maximumAge: 0,
                        timeout: Infinity,
                    }
                );
            } else {
                alert("GPS를 지원하지 않습니다");
            }
        }
        getLocation();
    </script>
</html>

yk/templates/my_ask.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Document</title>
    </head>
    <body>
        <p>my_ask</p>
        {% for ask in my_ask %}
        <div class="answerbox_{{ask.id}}">
            <p>{{ask.question}}</p>
            <label for="answer"></label>
            <input type="text" name="answer" placeholder="답변을 입력해주세요" />
            <button type="submit" onclick="onClickAnswer({{ask.id}})">{% csrf_token %} answer</button>
            <a href="{% url 'yk:report_ask' ask.id%}"><button onclick="ReportAsk({{ask.id}})">신고하기</button></a>
        </div>
        {% endfor %}
    </body>
    <script>
        const request = new XMLHttpRequest();

        const onClickAnswer = (id) => {
            const url = "/answer/";
            const input = document.querySelector(`.answerbox_${id} input`);
            const answer = input.value;
            request.open("POST", url, true);
            request.setRequestHeader("Content-Type", "application/x-www-form-urlencoded");
            request.send(JSON.stringify({ id, answer }));
        };

        const handleResponseAnswer = () => {
            if (request.status <= 400) {
                const { ask_id, answer } = JSON.parse(request.response);
                const div = document.querySelector(`.answerbox_${ask_id}`);
                div.style.display = "none";
            }
        };
        request.onreadystatechange = () => {
            if (request.readyState === XMLHttpRequest.DONE) {
                handleResponseAnswer();
            }
        };
    </script>
</html>

yk/templates/my_profile.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Document</title>
    </head>
    <body>
        <form action="" method="POST" enctype="multipart/form-data">
            <img src="{{profile.profile_image.url}}" alt="" width="100" />
            <h1>{{profile.nickname}}</h1>
            <p>{{profile.school}}/{{profile.gender}}/{{profile.age}}/{{profile.mbti}}</p>
            <p>{{profile.major}} {{profile.goal}}</p>
            <p>{{profile.club}}</p>
            <p>{{profile.address}}</p>
            {% for interest in profile.interest.all %}
            <p>#{{interest}}</p>
            {% endfor %}
        </form>
        <div></div>
        <div>
            {% for ask in asks %}
            <p>q. {{ask}}</p>
            {% for answer in ask.ask.all %}
            <p>a. {{answer}}</p>
            {% endfor %} {% endfor %}
        </div>
        <div>
            <a href="{% url 'yk:friends' %}">friends</a>
            <a href="{% url 'yk:my_ask' %}">my_ask</a>
        </div>
    </body>
</html>

yk/templates/old_join1.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Document</title>
    </head>
    <body>
        <form action="{% url 'yk:join1'%}" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <h3><label for="image">프로필 사진</label></h3>
            <input type="file" name="image" />
            <br />
            <label for="nickname">닉네임/이름</label>
            <input type="text" name="nickname" />
            <br />
            <label for="phone_number">전화번호</label>
            <input type="tel" name="phone_number" placeholder="- 없이 입력 ex)01012345678" />
            <br />
            <select name="school">
                <option>소속 대학교</option>
                <option value="yonsei">연세대학교</option>
                <option value="korea">고려대학교</option>
            </select>
            <input type="radio" value="block" name="block_school" />
            <label for="block_school">비공개</label>
            <input type="radio" value="show" name="block_school" checked="True" />
            <label for="block_school">공개</label>
            <br />
            <label for="age">나이</label>
            <input type="text" name="age" />
            <br />
            <select name="mbti">
                <option><h3>mbti</h3></option>
                <option value="entp"><h3>ENTP</h3></option>
                <option value="estp"><h3>ESTP</h3></option>
            </select>
            <br />
            <select name="gender">
                <option>성별</option>
                <option value="male">남성</option>
                <option value="female">여성</option>
            </select>
            <br />
            <h3><label for="bio">개성있는 자기소개</label></h3>
            <textarea name="bio"></textarea>
            <br />

            <button type="submit"><h4>제출</h4></button>
        </form>
        <a href="{% url 'yk:join2' %}">다음 페이지</a>
    </body>
</html>

yk/templates/old_join2.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Document</title>
    </head>
    <body>
        <form action="{% url 'yk:join2' %}" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <h1>어떤 사람인가요?</h1>
            <label><input type="radio" name="major" value="undergraduate" /> 대학생</label>
            <label><input type="radio" name="major" value="freshman" /> 신입생</label>
            <label><input type="radio" name="major" value="engineering" /> 공대생</label>

            <h1>현재 나의 목표는?</h1>
            <textarea name="goal"></textarea>
            <br />
            <button type="submit"><h4>제출</h4></button>
        </form>
        <a href="{% url 'yk:join3' %}">다음 페이지</a>
    </body>
</html>

yk/templates/old_join3.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Document</title>
    </head>
    <body>
        <h1>어떤 사람인가요?</h1>
        <form action="{% url 'yk:join3' %}" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <h3><label for="interest">관심사를 적어주세요</label></h3>
            <input type="text" name="interest" />
            <br />
            <h3><label for="club">활동 이력을 적어주세요</label></h3>
            <input type="text" name="club" />
            <br />
            <button type="submit"><h4>제출</h4></button>
        </form>
        <a href="{% url 'yk:join_done' %}">다음 페이지</a>
    </body>
</html>

yk/templates/profile.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Document</title>
    </head>

    <body>
        <div>
            <img src="{{friend_profile.profile_image.url}}" alt="" width="100" />
            <h1>{{friend_profile.nickname}}</h1>
            <p>{{friend_profile.school}}/{{friend_profile.gender}}/{{friend_profile.age}}/{{friend_profile.mbti}}</p>
            <p>{{friend_profile.major}} {{friend_profile.goal}}</p>
            <p>{{friend_profile.club}}</p>
            <p>{{friend_profile.address}}</p>
            {% for interest in friend_profile.interest.all %}
            <p>#{{interest}}</p>
            {% endfor %}
        </div>

        {% comment %}
        <div>
            <a href="{% url 'yk:ask' user.id%}"><button>ask</button></a>
        </div>
        {% endcomment %}

        <div>
            {% for ask in asks %}
            <p>q. {{ask}}</p>
            {% for answer in ask.ask.all %}
            <p>a. {{answer}} / {{answer.answered_at}}</p>
            {% endfor %} {% endfor %}
        </div>
        <div class="askbox">
            <input type="text" placeholder="친구에게 익명으로 ask를 해보세요!" />
            <button type="submit" onclick="onClickAsk({{ friend.id }})">{% csrf_token %} ask</button>
        </div>
        <br />
        <a href="{% url 'yk:profile' random_user.id%}"><button>넘기기</button></a>
        <a href="{% url 'yk:follow' friend_profile.user.id%}"><button>FRIENDS</button></a>
        <a href="{% url 'yk:report_user' friend_profile.user.id%}"><button onclick="ReportUser()">신고하기</button></a>
    </body>
    <script>
        const request = new XMLHttpRequest();

        const onClickAsk = (id) => {
            const url = "/ask/";
            const input = document.querySelector(`.askbox input`);
            const question = input.value;
            request.open("POST", url, true);
            request.setRequestHeader("Content-Type", "application/x-www-form-urlencoded");
            request.send(JSON.stringify({ id, question }));
        };

        const handleResponse = () => {
            if (request.status <= 400) {
                const { id, question } = JSON.parse(request.response);
                const input = document.querySelector(`.askbox input`);
                input.value = "";
                alert("질문을 완료했습니다!");
            }
        };

        request.onreadystatechange = () => {
            if (request.readyState === XMLHttpRequest.DONE) {
                handleResponse();
            }
        };

        const ReportUser = () => {
            confirm("신고하시겠습니까?");
        };
    </script>
</html>